# Zindi-New-User-Engagement-Prediction-Challenge
     Done by: Jeniffer Mukami
         Cosmus Mutuku
         
![3f96af13-4878-4db7-84d8-e3e486f61d7b.png](attachment:3f96af13-4878-4db7-84d8-e3e486f61d7b.png)

<a id="cont"></a>

## Table of Contents
<a href=#one>1. Introduction</a>

- <a href=#two>1.1 Overview</a>

- <a href=#two>1.2 Problem Statement</a>

<a href=#two>2. Comet Experiment</a>

<a href=#three>3. Loading Dependencies</a>

- <a href=#two>3.1 Import the libraries</a>

- <a href=#four>3.2 loading the data</a>

- <a href=#four>3.3 Data description and Summary Statistics </a>

<a href=#four>4. Exploratory Data Analysis</a>

<a href=#five>5. Modeling</a>

<a href=#six>6. Performance Evaluation</a>

<a href=#seven>7. Data Engineering</a>

<a href=#eight>8. Best Model Explanation</a>

- <a href=#eight>8.1 Zindi submission</a>

<a href=#nine>9. Conclusion</a>

<a id="one"></a>
## 1. Introduction
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

### Overview

Zindi is nothing without our users - you are the fuel in the rocket ship, the reason we do what we do. To make sure we are always providing the best possible user experience, we need to know if users will return to Zindi in their second month after signing up. We believe that if a user is constantly active at the start of their Zindi journey, this means that they are seeing value and will stick around. This is a good thing for us and for our users, as an active and healthy community means that we are adding value.

The objective of this challenge is to predict if a new user from a selected cohort will engage with Zindi in their second month on the platform. For example, if a user joined in June, will they be active in July?

This solution will help us establish and track our performance as a data science community and platform, and make sure that we are best serving the needs of you, our users! Help us make Zindi better for all of you.

### Problem Statement

Zindi needs to know if users will return to Zindi in their second month after signing up. We believe that if a user is constantly active at the start of their Zindi journey, this means that they are seeing value and will stick around.

The objective of this challenge is to predict if a new user from a selected cohort will engage with Zindi in their second month on the platform. For example, if a user joined in June, will they be active in July?

<a id="three"></a>
## 3. Loading Dependencies
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

### Import the libraries

In [63]:
#visualization
!pip install plotly
import plotly.express as px

import pandas as pd
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (5.5.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from plotly) (1.15.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly) (8.1.0)

### Loading the data

__Source__

The data is a subset of Zindi user activity. All variables have been masked to preserve privacy.

The objective of this challenge is to predict if a new user from a selected cohort will engage with Zindi in their second month on the platform. For example, if a user joined in January, will they be active in February?

Note there is no predefined train set for this challenge, you can create your own using the variables you think are most useful.

This challenge has a rolling leaderboard. This means you will need to constantly build on your model. We will be rolling out new user and competition information each month to simulate a real model development pipeline as you receive new data. The final users you will need to predict for are users created in months 5 and 6.

__Data Explanation__


blogs --This file contains information on the articles posted on the Learn page.

jobs --This file contains information on jobs posted on the Jobs board.

competitionparticipation --This file contains information about users' participation in hackathons and competitions.

comments --This file contains information about every comment made, such as which User_ID made the submission and when it was made.

Samplesubmission --Shows the submission format for this competition. The order of the rows does not matter, but the names of the ‘ID’ must be correct.

Discussion --This file contains information about every discussion made, such as which User_ID made the discussion and when it was made.

competition --This file contains information about hackathons and competitions.

users -- This file contains information about the users such as when they registered and which country they are from.

Useractivity --This file contains user activity from viewing or clicking on Zindi.

VariableDefinitions --This file explains each variable in each file.

***Variables***

In [16]:
variables=pd.read_csv("/content/VariableDefinitions.csv")
variables

,VariableName,VariableDefinition
0,Comments,NaN
1,UserID,This is the unique ID of the user who made the...
2,CommentDate Year,The year the comment was made in. Years are in...
3,CommentDate Month,The month of the year the comment was made in....
4,CommentDate Day_of_week,The day of the week the comment was made on. D...
...,...,...
56,UserDate Month,The month of the year the user signed up. Mont...
57,UserDate Day_of_week,The day of the week the user signed up on. Day...
58,NaN,NaN
59,NaN,NaN
60,The variables have been masked consistently ac...,NaN

***Sample Submission***

In [17]:
sample=pd.read_csv("/content/SampleSubmission.csv")
sample.head()

  User_ID_Next_month_Activity  Active
0         ID_4TOXNBGB_Month_5       0
1         ID_CHFTIP26_Month_5       0
2         ID_FU5GMWLQ_Month_5       0
3         ID_254TVBQP_Month_5       0
4         ID_4ENO2VFE_Month_5       0

***users***

In [18]:
users=pd.read_csv("/content/Users.csv")
users.head()

,FeatureX,FeatureY,User_ID,Countries_ID,Created At time,Created At Year,Created At Month,Created At Day_of_month
0,0,0,ID_DC6S4E9O,X9GR,19:33:13.663391,1,1,16
1,1,0,ID_E8S97OUT,X9GR,22:18:18.228921,1,12,27
2,0,0,ID_QZ1HASL3,X9GR,23:13:03.266635,1,1,1
3,1,0,ID_SDV9Q3E9,X9GR,09:50:09.697573,1,12,27
4,1,0,ID_W942LN7F,X9GR,13:33:06.531662,1,1,16

In [25]:
#Number of Users
len(set(users['User_ID']))

12413

In [26]:
#Number of featureY categories
len(set(users['FeatureY']))

3

In [33]:
users['FeatureY'].value_counts()

0    8114
1    3170
3    1129
Name: FeatureY, dtype: int64

In [66]:
fig = px.bar(users['FeatureY'].value_counts(), title='FeatureY', )
fig.show()

In [27]:
#Number of featureX categories
len(set(users['FeatureX']))

2

In [36]:
users['FeatureX'].value_counts()

0    11354
1     1059
Name: FeatureX, dtype: int64

In [68]:
fig = px.bar(users['FeatureX'].value_counts(), title='FeatureX', )
fig.show()

In [28]:
#Number of unique countries
len(set(users['Countries_ID']))

147

In [29]:
#Number of unique years
len(set(users['Created At Year']))

1

In [37]:
#All the users joined in the same year
users['Created At Year'].value_counts()

1    12413
Name: Created At Year, dtype: int64

In [38]:
#Get the number of members who joined in every month
users['Created At Month'].value_counts()

2     2278
5     2005
3     2000
12    1982
1     1504
4     1382
11    1262
Name: Created At Month, dtype: int64

In [69]:
fig = px.bar(users['Created At Month'].value_counts(), title='Months', )
fig.show()

In [39]:
#Get the number of accounts created in each day of a month
users['Created At Day_of_month'].value_counts()

27    721
29    574
26    510
20    495
6     473
22    456
25    453
5     443
4     438
3     433
28    424
13    421
1     406
19    405
24    400
11    394
7     391
12    382
21    367
23    366
8     361
18    359
15    358
14    350
2     340
17    339
9     316
30    315
16    285
10    269
31    169
Name: Created At Day_of_month, dtype: int64

In [70]:
fig = px.bar(users['Created At Day_of_month'].value_counts(), title='Days', )
fig.show()

In [44]:
#we may need to get the hour only from the time created
users['time_created'] = users['Created At time'].astype(str).str[0:2]
users.head()

,FeatureX,FeatureY,User_ID,Countries_ID,Created At time,Created At Year,Created At Month,Created At Day_of_month,time_created
0,0,0,ID_DC6S4E9O,X9GR,19:33:13.663391,1,1,16,19
1,1,0,ID_E8S97OUT,X9GR,22:18:18.228921,1,12,27,22
2,0,0,ID_QZ1HASL3,X9GR,23:13:03.266635,1,1,1,23
3,1,0,ID_SDV9Q3E9,X9GR,09:50:09.697573,1,12,27,09
4,1,0,ID_W942LN7F,X9GR,13:33:06.531662,1,1,16,13

In [46]:
#number of created accounts in every hour
users['time_created'].value_counts()

09    976
10    916
13    849
11    833
08    825
12    767
07    698
14    698
16    583
06    580
15    568
18    528
17    521
19    459
05    404
20    394
21    333
04    304
22    246
03    224
23    201
02    181
00    168
01    157
Name: time_created, dtype: int64

In [71]:
fig = px.bar(users['time_created'].value_counts(), title='time', )
fig.show()

***user Activity***

In [3]:
user_activity=pd.read_csv("/content/UserActivity.csv")
user_activity.head()

,User_ID,Title,datetime time,datetime Year,datetime Month,datetime Day_of_month
0,ID_RT43AK77,comp_ID_IV5D,22:00:38,1,11,22
1,ID_RT43AK77,comp_ID_IV5D,00:41:02,1,11,23
2,ID_RT43AK77,comp_ID_IV5D,00:53:15,1,11,23
3,ID_RT43AK77,comp_ID_IV5D,01:23:05,1,11,23
4,ID_RT43AK77,comp_ID_IV5D,01:27:38,1,11,23

In [79]:
user_activity.loc[user_activity['User_ID']=='ID_CEDNKSVV']

,User_ID,Title,datetime time,datetime Year,datetime Month,datetime Day_of_month
794,ID_CEDNKSVV,comp_ID_ZN92,20:03:02,1,12,16
1442,ID_CEDNKSVV,comp_ID_PDKH,15:51:17,1,12,27
1443,ID_CEDNKSVV,comp_ID_PDKH,20:23:18,1,12,14
1444,ID_CEDNKSVV,comp_ID_PDKH,02:00:25,1,12,15
1445,ID_CEDNKSVV,comp_ID_PDKH,18:12:08,1,1,7
...,...,...,...,...,...,...
88807,ID_CEDNKSVV,Viewed All Competitions,22:32:33,1,5,7
88808,ID_CEDNKSVV,Viewed All Discussions,23:34:11,1,5,7
317218,ID_CEDNKSVV,comp_ID_8DGC,16:04:36,1,5,1
317219,ID_CEDNKSVV,comp_ID_8DGC,22:58:18,1,5,1
317220,ID_CEDNKSVV,comp_ID_8DGC,20:44:42,1,5,2

In [76]:
user_activity['User_ID'].value_counts()

ID_CEDNKSVV    5169
ID_E7SKL6R4    2632
ID_KABHY0IT    1109
ID_TQM9E72F     986
ID_6FWILK4H     952
               ...
ID_7YEDYA97       1
ID_L8O5R7NO       1
ID_JYOFH5JP       1
ID_5F1GK0H5       1
ID_P3CVTPGE       1
Name: User_ID, Length: 10400, dtype: int64

In [77]:
user_activity['Title'].value_counts()

Viewed All Competitions            58176
Viewed All Discussions             47172
Viewed All Learning Pages          22930
Downloaded Competition Datafile    19578
Updated Profile                    14748
                                   ...
comp_ID_TJK9                           1
comp_ID_TBXU                           1
blog_ID_NVX3                           1
blog_ID_R97T                           1
blog_ID_22WI                           1
Name: Title, Length: 397, dtype: int64

***Jobs***

In [5]:
jobs=pd.read_csv("/content/Jobs.csv")
jobs.head()

,Remote,Experience,Industry,Employment Type,Company Size,Data Science Functions,job_ID
0,NaN,2-5,"{Government,Health,""Financial Services""}",fulltime,50-200,"{""Data modelling"",""Business/Data Analysis""}",ID_VJ43
1,NaN,NaN,NaN,NaN,NaN,NaN,ID_ZNZV
2,True,>5,NaN,fulltime,>200,"{""Data engineering"",""Data modelling""}",ID_PZHM
3,NaN,>5,{Media},fulltime,1-10,"{""Data engineering""}",ID_1PBU
4,NaN,1-2,{Media},fulltime,1-10,"{""Data engineering"",""Data modelling"",""ML Appli...",ID_ZTPN

***Discusion***

In [6]:
discussion=pd.read_csv("/content/Discussion.csv")
discussion.head()

,Competition ID,Personal,Theme,Disc_ID,User_ID,Created At time,Created At Year,Created At Month,Created At Day_of_month
0,GeneralDiscussion,1,NaN,ID_0BK7TH,ID_AAGFVLHH,19:48:26.862175,1,12,27
1,GeneralDiscussion,1,NaN,ID_ZFJ9J7,ID_0AJGQILU,09:37:52.039526,1,12,20
2,GeneralDiscussion,1,NaN,ID_ME45XX,ID_U90KK6KL,17:50:33.894800,1,2,9
3,ID_45W9,1,NaN,ID_2BG9IX,ID_U90KK6KL,07:57:55.178845,1,2,10
4,GeneralDiscussion,1,NaN,ID_251XVV,ID_F7HIGFHQ,19:56:13.041893,1,12,27

***Blogs***

In [8]:
blogs=pd.read_csv("/content/Blogs.csv")
blogs.head()

,Theme,blog_ID,Published At time,Published At Year,Published At Month,Published At Day_of_month
0,5.0,ID_Z6MM,10:34:55.071854,5,4,5
1,5.0,ID_7IB3,14:51:13.268049,5,4,5
2,3.0,ID_JR8K,13:19:08.877076,5,4,17
3,2.0,ID_IDAV,17:18:06.151314,5,7,6
4,2.0,ID_7JVL,11:48:36.428428,4,8,25

***Comments***

In [9]:
comments=pd.read_csv("/content/Comments.csv")
comments.head()

,Disc_ID,User_ID,Created At time,Created At Year,Created At Month,Created At Day_of_month
0,ID_ONQEAR,ID_CEDNKSVV,16:18:44.841697,1,5,11
1,ID_E0NHSS,ID_CEDNKSVV,17:30:40.566763,1,12,23
2,ID_3XKIOF,ID_CEDNKSVV,13:28:47.950841,1,1,3
3,ID_XCC6W4,ID_CEDNKSVV,18:42:17.362333,1,1,5
4,ID_OIGXGK,ID_CEDNKSVV,18:57:54.540062,1,12,19

,Disc_ID,User_ID,Created At time,Created At Year,Created At Month,Created At Day_of_month
0,ID_ONQEAR,ID_CEDNKSVV,16:18:44.841697,1,5,11
1,ID_E0NHSS,ID_CEDNKSVV,17:30:40.566763,1,12,23
2,ID_3XKIOF,ID_CEDNKSVV,13:28:47.950841,1,1,3
3,ID_XCC6W4,ID_CEDNKSVV,18:42:17.362333,1,1,5
4,ID_OIGXGK,ID_CEDNKSVV,18:57:54.540062,1,12,19

***Competitions***

In [ ]:
competitions=pd.read_csv("/content/Competition.csv")
competitions.head()

,FeatureA,FeatureB,FeatureC,FeatureD,FeatureE,SecretCode,FeatureF,FeatureG,FeatureH,FeatureI,Country_ID,Comp_ID,End Time time,End Time Year,End Time Month,End Time Day_of_month,Start Time time,Start Time Year,Start Time Month,Start Time Day_of_month
0,"[2, 4]",[14],15.0,0,2,1,[3],[],[],NaN,G3F0,ID_AU0T,21:05:00,2.0,6.0,19.0,07:00:00,2,6,19
1,[1],[],3.0,0,3,1,[1],[],[1],3.0,0Q35,ID_O21T,15:30:00,2.0,2.0,15.0,12:00:00,2,2,1
2,[1],[9],2.0,0,2,1,"[1, 5]",[5],[1],2.0,EGI9,ID_W6XE,21:59:00,2.0,5.0,9.0,08:00:00,2,3,28
3,[],[],1.0,0,2,1,[1],[4],[],NaN,NaN,ID_A2FN,12:00:00,2.0,6.0,22.0,12:00:00,2,6,12
4,[],[6],NaN,0,2,0,[],[4],[2],9.0,NaN,ID_X0PD,23:59:00,2.0,5.0,31.0,09:00:00,2,5,27

***Competitions Participation***

In [ ]:
competitionsp=pd.read_csv("/content/CompetitionPartipation.csv")
competitionsp.head()

,Competition ID,Participant Type,Successful Submission Count,User_ID,Created At time,Created At Year,Created At Month,Created At Day_of_month
0,ID_WPP3,1,NaN,ID_40G01FGV,19:38:04.689865,1,11,20
1,ID_ZN92,1,NaN,ID_40G01FGV,19:38:04.670583,1,11,20
2,ID_I9BN,1,NaN,ID_40G01FGV,12:06:55.884320,1,12,17
3,ID_PDKH,1,count 10,ID_40G01FGV,11:24:04.239058,1,12,6
4,ID_CFN7,1,NaN,ID_P33ABQX5,05:16:09.052129,1,5,26

In [ ]:
# import dataset
blogs = pd.read_csv('data/Blogs.csv')

comments = pd.read_csv('data/Comments.csv')
competition = pd.read_csv('data/Competition.csv')
competitionparticipation= pd.read_csv('data/CompetitionPartipation.csv')
discussion= pd.read_csv('data/Discussion.csv')
jobs= pd.read_csv('data/Jobs.csv')
Useractivity= pd.read_csv('data/UserActivity.csv')
Users= pd.read_csv('data/users.csv')
variabledefinitions=pd.read_csv('data/VariableDefinitions.csv')